sudo: required                          # provide travis sudo permissions.
services:                               # services travis need
  - docker

before_install:
  - docker build -t ranjithcheguri/docker-react -f Dockerfile.dev .      # build and tag image(-t).
  
script:
  - docker run ranjithcheguri/docker-react npm run test -- --coverage    # "-- --coverage" is to exit console after npm test, this return status is used by travis

deploy:
  provider: elasticbeanstalk                                             # using AWS ElasticBeanStalk for deployment
  region: "us-east-1"                                                    # get the region from beanstalk url, i.e ( DockerReact-env.uw9dhxntkp.us-east-1.elasticbeanstalk.com)
  app: "docker-react"                                                    # name setup in AWS beanstalk
  env: "DockerReact-env"                                                 # get from AWS beanstlak enviroment.
  bucket_name: "elasticbeanstalk-us-east-1-392320685985"                 # s3 bucket is automatically grab the bucket name with the help of region from s3 service. 
  bucket_path: "docker-react"                                            # by default will be app-name.
  on:
    branch: master                                                       # code is deployed only if changes are made to master branch.
  access_key_id: 
    secure: $AWS_ACCESS_KEY                                              # ACCESS KEY and SECRET KEY of IAM user generated for allowing access to beanstalk
  secret_access_key:
    secure: $AWS_SECRET_KEY